# # # Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

# # twig:
# #     form_themes:
# #         - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    #par défault le path démarre au dossier /public
    base_path: "bundles/ckeditor_custom"
    js_path:   "bundles/ckeditor_custom/ckeditor.js"
    # base_path: "bundles/fosckeditor"
    # js_path:   "bundles/fosckeditor/ckeditor.js"

    configs:
      my_config:
        # language: fr
        uiColor: "#32473A"
        codeSnippet_theme: 'monokai_sublime'
        codeSnippet_languages:
          - 'PHP'
          - 'SQL'
          - 'JavaScript'
          - 'Clingon'

        filebrowserBrowseRoute: elfinder
        filebrowserBrowseRouteParameters: []
        # codeSnippet_theme: 'pojoaque'

# fos_ck_editor:
#   configs:
#     main_config:
#       toolbar:
#         - {
#             name: "styles",
#             items:
#               [
#                 "Bold",
#                 "Italic",
#                 "Underline",
#                 "Strike",
#                 "Blockquote",
#                 "-",
#                 "Link",
#                 "-",
#                 "RemoveFormat",
#                 "-",
#                 "NumberedList",
#                 "BulletedList",
#                 "-",
#                 "Outdent",
#                 "Indent",
#                 "-",
#                 "-",
#                 "JustifyLeft",
#                 "JustifyCenter",
#                 "JustifyRight",
#                 "JustifyBlock",
#                 "-",
#                 "Image",
#                 "Table",
#                 "-",
#                 "Styles",
#                 "Format",
#                 "Font",
#                 "FontSize",
#                 "-",
#                 "TextColor",
#                 "BGColor",
#                 "Source",
#               ],
#           }