vich_uploader:
    db_driver: orm

    mappings:
       banner_images:
           uri_prefix: /images/banner
           upload_destination: '%kernel.project_dir%/public/images/banner'
           namer:    Vich\UploaderBundle\Naming\SmartUniqueNamer
